/**
 * A C header for what a library exports.
 *
 * REWRITE-PLAN §12.9 asks for header emission alongside the library targets,
 * and the reason is that a `static-lib` nobody can call is not a deliverable.
 * The C side needs declarations, and hand-writing them is how the two sides
 * come to disagree about a struct's field order six months later.
 *
 * Generated from the **MIR**, not from the TypeScript. By the time a module
 * reaches here every type is concrete and sized, the C ABI has already accepted
 * it, and struct layout is the layout the backend actually used. Reading the
 * AST again would be a second derivation of the same facts, and a second thing
 * to keep in step.
 *
 * Only `Linkage::Export` functions appear, because only those have a C
 * signature — an internal function is classified however is fastest and has no
 * stable shape to publish (REWRITE-PLAN §6).
 */

import type { Module, Signature, TyKind } from "@goblin-forge/backend";

export interface HeaderOptions {
  /** The library's name, used for the include guard and the banner. */
  readonly name: string;
}

/** Raised when an exported signature has no C spelling. */
export class HeaderError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "HeaderError";
  }
}

/**
 * Render a C header declaring everything `module` exports.
 *
 * The result is a complete translation unit's worth of declarations: an include
 * guard, the fixed-width integer types, every struct an exported signature
 * mentions, and then the functions.
 */
export function emitHeader(module: Module, options: HeaderOptions): string {
  const guard = `GOBLIN_${identifier(options.name).toUpperCase()}_H`;
  const out: string[] = [];

  out.push(`/* Generated by goblin-forge for \`${options.name}\`. Do not edit.`);
  out.push(" *");
  out.push(" * Every declaration here is `extern \"C\"`, classified by the platform's own");
  out.push(" * rules — Win64 or System V — so a C compiler and this one agree about");
  out.push(" * registers, stack slots and hidden return pointers without either side");
  out.push(" * being told.");
  out.push(" *");
  out.push(" * Link the Goblin runtime alongside this library. A Goblin archive carries");
  out.push(" * only its own objects, so that two of them in one program do not each bring");
  out.push(" * a copy of the runtime.");
  out.push(" */");
  out.push(`#ifndef ${guard}`);
  out.push(`#define ${guard}`);
  out.push("");
  out.push("#include <stdint.h>");
  out.push("#include <stdbool.h>");
  out.push("");
  out.push("#ifdef __cplusplus");
  out.push('extern "C" {');
  out.push("#endif");
  out.push("");

  if (usesStrings(module)) {
    out.push("/* A Goblin string.");
    out.push(" *");
    out.push(" * **Reading one is free.** It points at nul-terminated bytes, so `printf`,");
    out.push(" * `strlen` and every other `const char *` reader work on it unchanged.");
    out.push(" *");
    out.push(" * **Making one is not.** A length header sits sixteen bytes *behind* the");
    out.push(" * pointer, so a plain C string is not a GoblinString and passing one where");
    out.push(" * this type is expected reads a length out of whatever precedes your");
    out.push(" * literal. That is why this is a typedef and not `const char *`: the");
    out.push(" * compiler cannot stop you, so the name is the warning. Use");
    out.push(" * `gf_string_from_cstr`, which copies.");
    out.push(" *");
    out.push(" * **Freeing one is `gf_string_free`, never `free`** — the allocation starts");
    out.push(" * at the header, not at the pointer you were handed.");
    out.push(" *");
    out.push(" * Which strings you own is this library's business to document, exactly as");
    out.push(" * it is for any C API that hands out memory.");
    out.push(" */");
    out.push("typedef const char* GoblinString;");
    out.push("");
    out.push("GoblinString gf_string_from_cstr(const char* bytes);");
    out.push("GoblinString gf_string_clone(GoblinString s);");
    out.push("void gf_string_free(GoblinString s);");
    out.push("");
  }

  const structs = emitStructs(module);
  if (structs.length > 0) {
    out.push(...structs);
    out.push("");
  }

  let any = false;
  for (const func of module.funcs) {
    if (func.linkage !== "Export") continue;
    const signature = module.sigs[func.sig];
    if (signature === undefined) continue;
    out.push(declaration(module, sym(module, func.name), signature));
    any = true;
  }
  if (!any) {
    out.push("/* This library exports no functions. */");
  }

  out.push("");
  out.push("#ifdef __cplusplus");
  out.push("} /* extern \"C\" */");
  out.push("#endif");
  out.push("");
  out.push(`#endif /* ${guard} */`);
  return out.join("\n") + "\n";
}

/**
 * Struct definitions, in an order where each is defined before it is used.
 *
 * Nested aggregates are **inline** here as they are everywhere else, so a
 * struct genuinely contains its fields' bytes and the definition has to come
 * first — a forward declaration is not enough for a member of struct type.
 */
function emitStructs(module: Module): string[] {
  const order: number[] = [];
  const seen = new Set<number>();
  // Signatures reached through a callback. Each gets a `typedef`, because C's
  // declarator syntax for a function *returning* a function pointer —
  // `int32_t (*f(void))(int32_t)` — is unreadable and a name is not optional
  // anyway once one appears as a struct field.
  const fnPtrs = new Set<number>();

  // **Post-order.** A struct is appended after everything it contains, because
  // nested aggregates are inline: `Line` holds two `Point`s by value, so C
  // needs `Point`'s definition — not a forward declaration — before it. Marking
  // on the way *down* and appending there produces the reverse order, which
  // compiles for pointers and fails for exactly the case this language cares
  // about.
  const visit = (ty: number): void => {
    const kind = module.types[ty]?.kind;
    if (kind === undefined) return;
    if (kind.kind === "Struct") {
      if (seen.has(kind.value)) return;
      // Marked before recursing so a struct reached twice is emitted once. A
      // cycle cannot happen: it would need a struct containing itself by value,
      // which has no layout.
      seen.add(kind.value);
      for (const field of module.structs[kind.value]?.fields ?? []) visit(field.ty);
      order.push(kind.value);
      return;
    }
    if (kind.kind === "Pointer" || kind.kind === "Reference" || kind.kind === "Array") {
      visit(kind.value);
    }
    if (kind.kind === "FixedArray") visit(kind.element);
    // Through a callback's signature: a struct that appears only as a
    // callback's parameter still has to be declared before the callback is.
    if (kind.kind === "FnPtr") {
      const signature = module.sigs[kind.value];
      for (const param of signature?.params ?? []) visit(param.ty);
      if (signature !== undefined) visit(signature.ret);
      fnPtrs.add(kind.value);
    }
  };

  for (const func of module.funcs) {
    if (func.linkage !== "Export") continue;
    const signature = module.sigs[func.sig];
    if (signature === undefined) continue;
    for (const param of signature.params) visit(param.ty);
    visit(signature.ret);
  }

  const out: string[] = [];
  // Before the structs would be wrong — a callback may take one — and after
  // them is right for the same reason.
  for (const id of order) {
    const def = module.structs[id];
    if (def === undefined) continue;
    const name = identifier(sym(module, def.name));
    out.push(`typedef struct ${name} {`);
    for (const field of def.fields) {
      out.push(`    ${member(module, field.ty, identifier(sym(module, field.name)))};`);
    }
    out.push(`} ${name};`);
    out.push("");
  }
  for (const sig of [...fnPtrs].sort((a, b) => a - b)) {
    out.push(`typedef ${functionPointer(module, sig, fnPtrName(sig))};`);
    out.push("");
  }
  if (out.length > 0) out.pop();
  return out;
}

/**
 * The typedef name for a callback signature.
 *
 * By signature id, which is stable for a given program because the frontend
 * interns signatures in the order it meets them.
 */
function fnPtrName(sig: number): string {
  return `GfFn${sig}`;
}

function declaration(module: Module, name: string, signature: Signature): string {
  const params = signature.params.map((param, index) =>
    member(module, param.ty, `p${index}`),
  );
  if (signature.variadic) params.push("...");
  const list = params.length === 0 ? "void" : params.join(", ");
  return `${cType(module, signature.ret)} ${identifier(name)}(${list});`;
}

/**
 * A declarator: the C type with a name in the middle of it.
 *
 * Separate from {@link cType} because C's declarator syntax puts the name
 * *inside* the type for arrays — `int32_t xs[8]`, not `int32_t[8] xs` — and
 * writing the two as one string is how that gets silently wrong.
 */
function member(module: Module, ty: number, name: string): string {
  const kind = module.types[ty]?.kind;
  if (kind?.kind === "FixedArray") {
    return `${cType(module, kind.element)} ${name}[${kind.length}]`;
  }
  return `${cType(module, ty)} ${name}`;
}

/** `ret (*name)(params)`, with an empty name for an abstract declarator. */
function functionPointer(module: Module, sig: number, name: string): string {
  const signature = module.sigs[sig];
  if (signature === undefined) throw new HeaderError(`signature ${sig} is not in the module`);
  const params = signature.params.map((param) => cType(module, param.ty));
  if (signature.variadic) params.push("...");
  const list = params.length === 0 ? "void" : params.join(", ");
  return `${cType(module, signature.ret)} (*${name})(${list})`;
}

function cType(module: Module, ty: number): string {
  const kind = module.types[ty]?.kind;
  if (kind === undefined) throw new HeaderError(`type ${ty} is not in the module`);
  return spell(module, kind);
}

function spell(module: Module, kind: TyKind): string {
  switch (kind.kind) {
    case "Void":
      return "void";
    case "Bool":
      return "bool";
    case "Int":
      return INT_TYPES[kind.value] ?? "intptr_t";
    case "Float":
      return kind.value === "F32" ? "float" : "double";
    case "Pointer":
    case "Reference":
      return `${cType(module, kind.value)}*`;
    case "Struct":
      return identifier(sym(module, module.structs[kind.value]?.name ?? 0));
    case "FixedArray":
      // Only reachable through `member`, which handles it. A bare fixed array
      // as a parameter or return has no C spelling — C cannot pass one by
      // value — and the ABI classifier rejects it before this is asked.
      return `${cType(module, kind.element)}*`;
    // Spelled as its own typedef rather than as `const char *`, and the
    // difference is the whole point. Reading one *is* just a `const char *`.
    // But the length header sits behind the pointer, so a C literal is not one
    // — and a header that says `const char *` invites exactly that mistake,
    // which reads a length from whatever precedes the literal and is silently
    // wrong rather than loudly. The name is the only warning available.
    case "Str":
      return "GoblinString";
    // The other half of the pair, and the whole reason the pair exists: a
    // signature can now say which of the two it means. This one really is a
    // plain `const char *`, and whether the caller owns it is documentation.
    case "CStr":
      return "const char*";
    // These own something, or carry a vtable. `require_plain_data` in the ABI
    // classifier refuses them at the boundary, so reaching here means the two
    // halves disagree about what may cross.
    // Its typedef, not an inline declarator. C's syntax for a function
    // *returning* a function pointer puts the parameter list on the outside —
    // `int32_t (*pick(bool))(int32_t)` — which a `${ret} ${name}(${params})`
    // template cannot produce and nobody wants to read. The typedef makes a
    // callback an ordinary noun everywhere it appears.
    case "FnPtr":
      return fnPtrName(kind.value);
    case "Array":
    case "Class":
    case "Interface":
      throw new HeaderError(
        `\`${kind.kind}\` has no C spelling. The ABI classifier is meant to have ` +
          "rejected this before a header was asked for.",
      );
  }
}

const INT_TYPES: Record<string, string> = {
  I8: "int8_t",
  I16: "int16_t",
  I32: "int32_t",
  I64: "int64_t",
  U8: "uint8_t",
  U16: "uint16_t",
  U32: "uint32_t",
  U64: "uint64_t",
  Isize: "intptr_t",
  Usize: "uintptr_t",
};

/** Whether any exported signature mentions a `string`. */
function usesStrings(module: Module): boolean {
  const isStr = (ty: number): boolean => module.types[ty]?.kind.kind === "Str";
  return module.funcs.some((func) => {
    if (func.linkage !== "Export") return false;
    const signature = module.sigs[func.sig];
    if (signature === undefined) return false;
    return signature.params.some((param) => isStr(param.ty)) || isStr(signature.ret);
  });
}

function sym(module: Module, id: number): string {
  return module.strings[id] ?? `sym${id}`;
}

/**
 * A name C will accept.
 *
 * Anonymous struct names are built from their field list — `{x,y}` — which is
 * a fine key and not an identifier.
 */
function identifier(name: string): string {
  const cleaned = name.replace(/[^A-Za-z0-9_]/g, "_");
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}
