// @generated by `cargo run -p goblin-mir --bin gen-bindings`. DO NOT EDIT.
//
// The MIR is defined once, in Rust, in crates/goblin-mir. This file is that
// definition projected into TypeScript, encoder included.
//
// postcard is not self-describing: struct fields and enum variants are
// positional, and no name ever reaches the wire. That is why the encoder is
// generated too. A hand-written one that drifted by a single field would not
// fail to decode — it would decode into a different, perfectly plausible
// module, which is the failure mode this whole arrangement exists to remove.

/** Fingerprint of the wire format these bindings were generated from. */
export const SCHEMA_FINGERPRINT = 0xfb0eb16471f939bbn;

/** The same value as hex, for comparing against the addon's report. */
export const SCHEMA_FINGERPRINT_HEX = "fb0eb16471f939bb";

// ---------------------------------------------------------------------------
// postcard writer
// ---------------------------------------------------------------------------

const UTF8 = new TextEncoder();

/**
 * A growable little-endian byte sink implementing postcard's primitive
 * encodings: LEB128 varints for anything wider than a byte, zigzag for signed
 * values, raw IEEE-754 bytes for floats, and a varint length prefix for
 * anything with a length.
 */
export class Writer {
  #buf: Uint8Array;
  #view: DataView;
  #len = 0;

  constructor(capacity = 1 << 16) {
    this.#buf = new Uint8Array(capacity);
    this.#view = new DataView(this.#buf.buffer);
  }

  #reserve(extra: number): void {
    const needed = this.#len + extra;
    if (needed <= this.#buf.length) return;
    let capacity = this.#buf.length * 2;
    while (capacity < needed) capacity *= 2;
    const grown = new Uint8Array(capacity);
    grown.set(this.#buf.subarray(0, this.#len));
    this.#buf = grown;
    this.#view = new DataView(grown.buffer);
  }

  u8(value: number): void {
    this.#reserve(1);
    this.#buf[this.#len++] = value & 0xff;
  }

  i8(value: number): void {
    this.u8(value < 0 ? value + 0x100 : value);
  }

  bool(value: boolean): void {
    this.u8(value ? 1 : 0);
  }

  /** LEB128, for u16/u32 and anything that fits an f64 exactly. */
  varint(value: number): void {
    this.#reserve(5);
    let rest = value >>> 0;
    while (rest > 0x7f) {
      this.#buf[this.#len++] = (rest & 0x7f) | 0x80;
      rest >>>= 7;
    }
    this.#buf[this.#len++] = rest;
  }

  /** LEB128 over a bigint, for the 64- and 128-bit widths. */
  varintBig(value: bigint): void {
    this.#reserve(19);
    let rest = value;
    while (rest > 0x7fn) {
      this.#buf[this.#len++] = Number(rest & 0x7fn) | 0x80;
      rest >>= 7n;
    }
    this.#buf[this.#len++] = Number(rest);
  }

  /** Zigzag then varint, which is how postcard encodes signed integers. */
  varintSigned(value: number, bits: number): void {
    const shifted = value < 0 ? -value * 2 - 1 : value * 2;
    if (bits <= 32) this.varint(shifted);
    else this.varintBig(BigInt(shifted));
  }

  varintSignedBig(value: bigint): void {
    this.varintBig(value < 0n ? -value * 2n - 1n : value * 2n);
  }

  f32(value: number): void {
    this.#reserve(4);
    this.#view.setFloat32(this.#len, value, true);
    this.#len += 4;
  }

  f64(value: number): void {
    this.#reserve(8);
    this.#view.setFloat64(this.#len, value, true);
    this.#len += 8;
  }

  bytes(value: Uint8Array): void {
    this.varint(value.length);
    this.#reserve(value.length);
    this.#buf.set(value, this.#len);
    this.#len += value.length;
  }

  str(value: string): void {
    // encodeInto avoids the intermediate array for the common ASCII case, but
    // needs room for the worst case before the length is known, so measure
    // first for anything long enough for the difference to matter.
    const encoded = UTF8.encode(value);
    this.bytes(encoded);
  }

  finish(): Uint8Array {
    return this.#buf.subarray(0, this.#len);
  }

  get length(): number {
    return this.#len;
  }
}

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * One brand key, one string literal per id type.
 *
 * The same trick the language's own fixed-width types use (REWRITE-PLAN §7),
 * and for the same reason: a distinct key per id would leave every brand
 * optional-and-absent from the others, and optional-and-absent is assignable,
 * so the ids would silently unify. Here the brand is *required* rather than
 * optional, because ids come from builders rather than from literals — there is
 * no `const x: LocalId = 3` to keep readable, and a raw `number` slipping into
 * an id position is exactly the mistake worth catching.
 */
declare const GfIdBrand: unique symbol;

export type SymId = number & { readonly [GfIdBrand]: "SymId" };
export const SymId = (raw: number): SymId => raw as SymId;

export type IntTy =
  | "I8"
  | "I16"
  | "I32"
  | "I64"
  | "U8"
  | "U16"
  | "U32"
  | "U64"
  | "Isize"
  | "Usize";

export type FloatTy =
  | "F32"
  | "F64";

export type TyId = number & { readonly [GfIdBrand]: "TyId" };
export const TyId = (raw: number): TyId => raw as TyId;

export type SigId = number & { readonly [GfIdBrand]: "SigId" };
export const SigId = (raw: number): SigId => raw as SigId;

export type StructId = number & { readonly [GfIdBrand]: "StructId" };
export const StructId = (raw: number): StructId => raw as StructId;

export type ClassId = number & { readonly [GfIdBrand]: "ClassId" };
export const ClassId = (raw: number): ClassId => raw as ClassId;

export type InterfaceId = number & { readonly [GfIdBrand]: "InterfaceId" };
export const InterfaceId = (raw: number): InterfaceId => raw as InterfaceId;

export type TyKind =
  | { kind: "Void" }
  | { kind: "Bool" }
  | { kind: "Int"; value: IntTy }
  | { kind: "Float"; value: FloatTy }
  | { kind: "Simd"; elem: FloatTy; lanes: number }
  | { kind: "Pointer"; value: TyId }
  | { kind: "Reference"; value: TyId }
  | { kind: "FnPtr"; value: SigId }
  | { kind: "Str" }
  | { kind: "CStr" }
  | { kind: "Array"; value: TyId }
  | { kind: "FixedArray"; element: TyId; length: bigint }
  | { kind: "Struct"; value: StructId }
  | { kind: "Class"; value: ClassId }
  | { kind: "Interface"; value: InterfaceId }
  | { kind: "Opaque"; value: SymId }
;

export type Category =
  | "Trivial"
  | "Owning"
  | "Polymorphic"
  | "Borrow";

export interface TyDef {
  kind: TyKind;
  category: Category;
}

export type FileId = number & { readonly [GfIdBrand]: "FileId" };
export const FileId = (raw: number): FileId => raw as FileId;

export interface Span {
  file: FileId;
  line: number;
  col: number;
}

export interface FieldDef {
  name: SymId;
  ty: TyId;
  span: Span;
}

export interface StructDef {
  name: SymId;
  fields: FieldDef[];
  cCompatible: boolean;
  union: boolean;
  span: Span;
}

export type FuncId = number & { readonly [GfIdBrand]: "FuncId" };
export const FuncId = (raw: number): FuncId => raw as FuncId;

export interface Impl {
  interface: InterfaceId;
  methods: FuncId[];
}

export interface ClassDef {
  name: SymId;
  base: ClassId | null;
  fields: FieldDef[];
  ownFields: number;
  vtable: FuncId[];
  implements: Impl[];
  span: Span;
}

export interface InterfaceMethod {
  name: SymId;
  sig: SigId;
}

export interface InterfaceDef {
  name: SymId;
  key: bigint;
  methods: InterfaceMethod[];
  span: Span;
}

export interface Param {
  ty: TyId;
  name: SymId | null;
}

export type Abi =
  | "Internal"
  | "C";

export interface Signature {
  params: Param[];
  ret: TyId;
  abi: Abi;
  variadic: boolean;
}

export interface ExternFunc {
  name: SymId;
  sig: SigId;
  span: Span;
}

export type Linkage =
  | "Internal"
  | "Export";

export interface Global {
  name: SymId;
  ty: TyId;
  linkage: Linkage;
  mutable: boolean;
  init: Uint8Array | null;
  span: Span;
}

export type StorageClass =
  | "Owned"
  | "Inline"
  | "Borrowed"
  | "Temporary";

export interface LocalDecl {
  ty: TyId;
  storage: StorageClass;
  name: SymId | null;
  span: Span;
}

export type BlockKind =
  | "Normal"
  | "Cleanup";

export type LocalId = number & { readonly [GfIdBrand]: "LocalId" };
export const LocalId = (raw: number): LocalId => raw as LocalId;

export type FieldId = number & { readonly [GfIdBrand]: "FieldId" };
export const FieldId = (raw: number): FieldId => raw as FieldId;

export type Projection =
  | { kind: "Deref" }
  | { kind: "Field"; value: FieldId }
  | { kind: "Index"; value: LocalId }
  | { kind: "ConstIndex"; value: bigint }
;

export interface Place {
  local: LocalId;
  projection: Projection[];
}

export type ExternId = number & { readonly [GfIdBrand]: "ExternId" };
export const ExternId = (raw: number): ExternId => raw as ExternId;

export type FuncRef =
  | { kind: "Local"; value: FuncId }
  | { kind: "Extern"; value: ExternId }
;

export type Const =
  | { kind: "Unit" }
  | { kind: "Bool"; value: boolean; ty: TyId }
  | { kind: "Int"; bits: bigint; ty: TyId }
  | { kind: "Float"; bits: bigint; ty: TyId }
  | { kind: "Null"; value: TyId }
  | { kind: "Str"; text: SymId; ty: TyId }
  | { kind: "Func"; func: FuncRef; ty: TyId }
;

export type Operand =
  | { kind: "Copy"; value: Place }
  | { kind: "Move"; value: Place }
  | { kind: "Borrow"; value: Place }
  | { kind: "Const"; value: Const }
;

export type BinOp =
  | "Add"
  | "Sub"
  | "Mul"
  | "Div"
  | "Rem"
  | "BitAnd"
  | "BitOr"
  | "BitXor"
  | "Shl"
  | "Shr"
  | "Eq"
  | "Ne"
  | "Lt"
  | "Le"
  | "Gt"
  | "Ge";

export type UnOp =
  | "Neg"
  | "BitNot"
  | "Not";

export type CastKind =
  | "IntToInt"
  | "IntToFloat"
  | "FloatToInt"
  | "FloatToFloat"
  | "BoolToInt"
  | "PtrToPtr"
  | "PtrToInt"
  | "IntToPtr";

export type SimdBinOp =
  | "Add"
  | "Sub"
  | "Mul"
  | "Div"
  | "Min"
  | "Max";

export type SimdUnOp =
  | "Neg"
  | "Abs"
  | "Sqrt"
  | "Floor"
  | "Ceil"
  | "Round"
  | "Trunc";

export type Rvalue =
  | { kind: "Use"; value: Operand }
  | { kind: "Default" }
  | { kind: "Binary"; op: BinOp; lhs: Operand; rhs: Operand }
  | { kind: "Unary"; op: UnOp; operand: Operand }
  | { kind: "Cast"; op: CastKind; operand: Operand; to: TyId }
  | { kind: "Ref"; value: Place }
  | { kind: "AddrOf"; value: Place }
  | { kind: "Aggregate"; ty: TyId; fields: Operand[] }
  | { kind: "Len"; value: Place }
  | { kind: "MakeInterface"; interface: InterfaceId; class: ClassId; source: Place }
  | { kind: "TryInterface"; interface: InterfaceId; source: Place }
  | { kind: "TryClass"; class: ClassId; source: Place }
  | { kind: "InterfaceIsNull"; value: Place }
  | { kind: "ArrayPushSlot"; value: Place }
  | { kind: "SizeOf"; value: TyId }
  | { kind: "AlignOf"; value: TyId }
  | { kind: "Select"; cond: Operand; ifTrue: Operand; ifFalse: Operand }
  | { kind: "SimdLoad"; source: Place; ty: TyId }
  | { kind: "SimdStore"; vector: Operand }
  | { kind: "SimdFromParts"; lanes: Operand[]; ty: TyId }
  | { kind: "SimdExtract"; vector: Operand; lane: number }
  | { kind: "SimdSplat"; value: Operand; ty: TyId }
  | { kind: "SimdBinary"; op: SimdBinOp; lhs: Operand; rhs: Operand }
  | { kind: "SimdUnary"; op: SimdUnOp; operand: Operand }
  | { kind: "SimdShuffle"; lhs: Operand; rhs: Operand; mask: Uint8Array; ty: TyId }
  | { kind: "SimdFma"; a: Operand; b: Operand; c: Operand }
;

export type BlockId = number & { readonly [GfIdBrand]: "BlockId" };
export const BlockId = (raw: number): BlockId => raw as BlockId;

export type UnwindAction =
  | { kind: "Continue" }
  | { kind: "Cleanup"; value: BlockId }
  | { kind: "Unreachable" }
  | { kind: "Terminate" }
;

export type Statement =
  | { kind: "Assign"; place: Place; rvalue: Rvalue }
  | { kind: "Init"; place: Place; rvalue: Rvalue }
  | { kind: "Drop"; place: Place; flag: LocalId | null; unwind: UnwindAction }
  | { kind: "StorageLive"; value: LocalId }
  | { kind: "StorageDead"; value: LocalId }
  | { kind: "SetDropFlag"; flag: LocalId; value: boolean }
  | { kind: "Nop" }
;

export interface SwitchTarget {
  value: bigint;
  block: BlockId;
}

export type Callee =
  | { kind: "Direct"; value: FuncRef }
  | { kind: "Indirect"; operand: Operand; sig: SigId }
  | { kind: "Virtual"; slot: number; sig: SigId }
  | { kind: "Interface"; slot: number; sig: SigId }
;

export interface CallDest {
  place: Place;
  target: BlockId;
}

export type AbortReason =
  | "BoundsCheck"
  | "DivideByZero"
  | "NullDeref"
  | "UnwindAcrossBoundary";

export type Terminator =
  | { kind: "Goto"; value: BlockId }
  | { kind: "Branch"; cond: Operand; thenBlock: BlockId; elseBlock: BlockId }
  | { kind: "Switch"; discr: Operand; targets: SwitchTarget[]; default: BlockId }
  | { kind: "Call"; callee: Callee; args: Operand[]; destination: CallDest | null; unwind: UnwindAction }
  | { kind: "Return" }
  | { kind: "Unreachable" }
  | { kind: "Resume" }
  | { kind: "Abort"; value: AbortReason }
;

export interface Block {
  kind: BlockKind;
  statements: Statement[];
  terminator: Terminator;
}

export interface Function {
  name: SymId;
  sig: SigId;
  linkage: Linkage;
  locals: LocalDecl[];
  blocks: Block[];
  span: Span;
}

export interface Module {
  schemaFingerprint: bigint;
  name: SymId;
  strings: string[];
  files: string[];
  types: TyDef[];
  structs: StructDef[];
  classes: ClassDef[];
  interfaces: InterfaceDef[];
  sigs: Signature[];
  externs: ExternFunc[];
  globals: Global[];
  funcs: Function[];
}

// ---------------------------------------------------------------------------
// Encoders
// ---------------------------------------------------------------------------

export function writeSymId(w: Writer, v: SymId): void {
  w.varint(v);
}

const IntTyIndex: Record<IntTy, number> = {
  I8: 0,
  I16: 1,
  I32: 2,
  I64: 3,
  U8: 4,
  U16: 5,
  U32: 6,
  U64: 7,
  Isize: 8,
  Usize: 9,
};

export function writeIntTy(w: Writer, v: IntTy): void {
  w.varint(IntTyIndex[v]);
}

const FloatTyIndex: Record<FloatTy, number> = {
  F32: 0,
  F64: 1,
};

export function writeFloatTy(w: Writer, v: FloatTy): void {
  w.varint(FloatTyIndex[v]);
}

export function writeTyId(w: Writer, v: TyId): void {
  w.varint(v);
}

export function writeSigId(w: Writer, v: SigId): void {
  w.varint(v);
}

export function writeStructId(w: Writer, v: StructId): void {
  w.varint(v);
}

export function writeClassId(w: Writer, v: ClassId): void {
  w.varint(v);
}

export function writeInterfaceId(w: Writer, v: InterfaceId): void {
  w.varint(v);
}

export function writeTyKind(w: Writer, v: TyKind): void {
  switch (v.kind) {
    case "Void": {
      w.varint(0);
      break;
    }
    case "Bool": {
      w.varint(1);
      break;
    }
    case "Int": {
      w.varint(2);
      writeIntTy(w, v.value);
      break;
    }
    case "Float": {
      w.varint(3);
      writeFloatTy(w, v.value);
      break;
    }
    case "Simd": {
      w.varint(4);
      writeFloatTy(w, v.elem);
      w.u8(v.lanes);
      break;
    }
    case "Pointer": {
      w.varint(5);
      writeTyId(w, v.value);
      break;
    }
    case "Reference": {
      w.varint(6);
      writeTyId(w, v.value);
      break;
    }
    case "FnPtr": {
      w.varint(7);
      writeSigId(w, v.value);
      break;
    }
    case "Str": {
      w.varint(8);
      break;
    }
    case "CStr": {
      w.varint(9);
      break;
    }
    case "Array": {
      w.varint(10);
      writeTyId(w, v.value);
      break;
    }
    case "FixedArray": {
      w.varint(11);
      writeTyId(w, v.element);
      w.varintBig(v.length);
      break;
    }
    case "Struct": {
      w.varint(12);
      writeStructId(w, v.value);
      break;
    }
    case "Class": {
      w.varint(13);
      writeClassId(w, v.value);
      break;
    }
    case "Interface": {
      w.varint(14);
      writeInterfaceId(w, v.value);
      break;
    }
    case "Opaque": {
      w.varint(15);
      writeSymId(w, v.value);
      break;
    }
  }
}

const CategoryIndex: Record<Category, number> = {
  Trivial: 0,
  Owning: 1,
  Polymorphic: 2,
  Borrow: 3,
};

export function writeCategory(w: Writer, v: Category): void {
  w.varint(CategoryIndex[v]);
}

export function writeTyDef(w: Writer, v: TyDef): void {
  writeTyKind(w, v.kind);
  writeCategory(w, v.category);
}

export function writeFileId(w: Writer, v: FileId): void {
  w.varint(v);
}

export function writeSpan(w: Writer, v: Span): void {
  writeFileId(w, v.file);
  w.varint(v.line);
  w.varint(v.col);
}

export function writeFieldDef(w: Writer, v: FieldDef): void {
  writeSymId(w, v.name);
  writeTyId(w, v.ty);
  writeSpan(w, v.span);
}

export function writeStructDef(w: Writer, v: StructDef): void {
  writeSymId(w, v.name);
  w.varint(v.fields.length); for (const item of v.fields) { writeFieldDef(w, item); }
  w.bool(v.cCompatible);
  w.bool(v.union);
  writeSpan(w, v.span);
}

export function writeFuncId(w: Writer, v: FuncId): void {
  w.varint(v);
}

export function writeImpl(w: Writer, v: Impl): void {
  writeInterfaceId(w, v.interface);
  w.varint(v.methods.length); for (const item of v.methods) { writeFuncId(w, item); }
}

export function writeClassDef(w: Writer, v: ClassDef): void {
  writeSymId(w, v.name);
  if (v.base === null) { w.u8(0); } else { w.u8(1); writeClassId(w, v.base!); }
  w.varint(v.fields.length); for (const item of v.fields) { writeFieldDef(w, item); }
  w.varint(v.ownFields);
  w.varint(v.vtable.length); for (const item of v.vtable) { writeFuncId(w, item); }
  w.varint(v.implements.length); for (const item of v.implements) { writeImpl(w, item); }
  writeSpan(w, v.span);
}

export function writeInterfaceMethod(w: Writer, v: InterfaceMethod): void {
  writeSymId(w, v.name);
  writeSigId(w, v.sig);
}

export function writeInterfaceDef(w: Writer, v: InterfaceDef): void {
  writeSymId(w, v.name);
  w.varintBig(v.key);
  w.varint(v.methods.length); for (const item of v.methods) { writeInterfaceMethod(w, item); }
  writeSpan(w, v.span);
}

export function writeParam(w: Writer, v: Param): void {
  writeTyId(w, v.ty);
  if (v.name === null) { w.u8(0); } else { w.u8(1); writeSymId(w, v.name!); }
}

const AbiIndex: Record<Abi, number> = {
  Internal: 0,
  C: 1,
};

export function writeAbi(w: Writer, v: Abi): void {
  w.varint(AbiIndex[v]);
}

export function writeSignature(w: Writer, v: Signature): void {
  w.varint(v.params.length); for (const item of v.params) { writeParam(w, item); }
  writeTyId(w, v.ret);
  writeAbi(w, v.abi);
  w.bool(v.variadic);
}

export function writeExternFunc(w: Writer, v: ExternFunc): void {
  writeSymId(w, v.name);
  writeSigId(w, v.sig);
  writeSpan(w, v.span);
}

const LinkageIndex: Record<Linkage, number> = {
  Internal: 0,
  Export: 1,
};

export function writeLinkage(w: Writer, v: Linkage): void {
  w.varint(LinkageIndex[v]);
}

export function writeGlobal(w: Writer, v: Global): void {
  writeSymId(w, v.name);
  writeTyId(w, v.ty);
  writeLinkage(w, v.linkage);
  w.bool(v.mutable);
  if (v.init === null) { w.u8(0); } else { w.u8(1); w.bytes(v.init!); }
  writeSpan(w, v.span);
}

const StorageClassIndex: Record<StorageClass, number> = {
  Owned: 0,
  Inline: 1,
  Borrowed: 2,
  Temporary: 3,
};

export function writeStorageClass(w: Writer, v: StorageClass): void {
  w.varint(StorageClassIndex[v]);
}

export function writeLocalDecl(w: Writer, v: LocalDecl): void {
  writeTyId(w, v.ty);
  writeStorageClass(w, v.storage);
  if (v.name === null) { w.u8(0); } else { w.u8(1); writeSymId(w, v.name!); }
  writeSpan(w, v.span);
}

const BlockKindIndex: Record<BlockKind, number> = {
  Normal: 0,
  Cleanup: 1,
};

export function writeBlockKind(w: Writer, v: BlockKind): void {
  w.varint(BlockKindIndex[v]);
}

export function writeLocalId(w: Writer, v: LocalId): void {
  w.varint(v);
}

export function writeFieldId(w: Writer, v: FieldId): void {
  w.varint(v);
}

export function writeProjection(w: Writer, v: Projection): void {
  switch (v.kind) {
    case "Deref": {
      w.varint(0);
      break;
    }
    case "Field": {
      w.varint(1);
      writeFieldId(w, v.value);
      break;
    }
    case "Index": {
      w.varint(2);
      writeLocalId(w, v.value);
      break;
    }
    case "ConstIndex": {
      w.varint(3);
      w.varintBig(v.value);
      break;
    }
  }
}

export function writePlace(w: Writer, v: Place): void {
  writeLocalId(w, v.local);
  w.varint(v.projection.length); for (const item of v.projection) { writeProjection(w, item); }
}

export function writeExternId(w: Writer, v: ExternId): void {
  w.varint(v);
}

export function writeFuncRef(w: Writer, v: FuncRef): void {
  switch (v.kind) {
    case "Local": {
      w.varint(0);
      writeFuncId(w, v.value);
      break;
    }
    case "Extern": {
      w.varint(1);
      writeExternId(w, v.value);
      break;
    }
  }
}

export function writeConst(w: Writer, v: Const): void {
  switch (v.kind) {
    case "Unit": {
      w.varint(0);
      break;
    }
    case "Bool": {
      w.varint(1);
      w.bool(v.value);
      writeTyId(w, v.ty);
      break;
    }
    case "Int": {
      w.varint(2);
      w.varintBig(v.bits);
      writeTyId(w, v.ty);
      break;
    }
    case "Float": {
      w.varint(3);
      w.varintBig(v.bits);
      writeTyId(w, v.ty);
      break;
    }
    case "Null": {
      w.varint(4);
      writeTyId(w, v.value);
      break;
    }
    case "Str": {
      w.varint(5);
      writeSymId(w, v.text);
      writeTyId(w, v.ty);
      break;
    }
    case "Func": {
      w.varint(6);
      writeFuncRef(w, v.func);
      writeTyId(w, v.ty);
      break;
    }
  }
}

export function writeOperand(w: Writer, v: Operand): void {
  switch (v.kind) {
    case "Copy": {
      w.varint(0);
      writePlace(w, v.value);
      break;
    }
    case "Move": {
      w.varint(1);
      writePlace(w, v.value);
      break;
    }
    case "Borrow": {
      w.varint(2);
      writePlace(w, v.value);
      break;
    }
    case "Const": {
      w.varint(3);
      writeConst(w, v.value);
      break;
    }
  }
}

const BinOpIndex: Record<BinOp, number> = {
  Add: 0,
  Sub: 1,
  Mul: 2,
  Div: 3,
  Rem: 4,
  BitAnd: 5,
  BitOr: 6,
  BitXor: 7,
  Shl: 8,
  Shr: 9,
  Eq: 10,
  Ne: 11,
  Lt: 12,
  Le: 13,
  Gt: 14,
  Ge: 15,
};

export function writeBinOp(w: Writer, v: BinOp): void {
  w.varint(BinOpIndex[v]);
}

const UnOpIndex: Record<UnOp, number> = {
  Neg: 0,
  BitNot: 1,
  Not: 2,
};

export function writeUnOp(w: Writer, v: UnOp): void {
  w.varint(UnOpIndex[v]);
}

const CastKindIndex: Record<CastKind, number> = {
  IntToInt: 0,
  IntToFloat: 1,
  FloatToInt: 2,
  FloatToFloat: 3,
  BoolToInt: 4,
  PtrToPtr: 5,
  PtrToInt: 6,
  IntToPtr: 7,
};

export function writeCastKind(w: Writer, v: CastKind): void {
  w.varint(CastKindIndex[v]);
}

const SimdBinOpIndex: Record<SimdBinOp, number> = {
  Add: 0,
  Sub: 1,
  Mul: 2,
  Div: 3,
  Min: 4,
  Max: 5,
};

export function writeSimdBinOp(w: Writer, v: SimdBinOp): void {
  w.varint(SimdBinOpIndex[v]);
}

const SimdUnOpIndex: Record<SimdUnOp, number> = {
  Neg: 0,
  Abs: 1,
  Sqrt: 2,
  Floor: 3,
  Ceil: 4,
  Round: 5,
  Trunc: 6,
};

export function writeSimdUnOp(w: Writer, v: SimdUnOp): void {
  w.varint(SimdUnOpIndex[v]);
}

export function writeRvalue(w: Writer, v: Rvalue): void {
  switch (v.kind) {
    case "Use": {
      w.varint(0);
      writeOperand(w, v.value);
      break;
    }
    case "Default": {
      w.varint(1);
      break;
    }
    case "Binary": {
      w.varint(2);
      writeBinOp(w, v.op);
      writeOperand(w, v.lhs);
      writeOperand(w, v.rhs);
      break;
    }
    case "Unary": {
      w.varint(3);
      writeUnOp(w, v.op);
      writeOperand(w, v.operand);
      break;
    }
    case "Cast": {
      w.varint(4);
      writeCastKind(w, v.op);
      writeOperand(w, v.operand);
      writeTyId(w, v.to);
      break;
    }
    case "Ref": {
      w.varint(5);
      writePlace(w, v.value);
      break;
    }
    case "AddrOf": {
      w.varint(6);
      writePlace(w, v.value);
      break;
    }
    case "Aggregate": {
      w.varint(7);
      writeTyId(w, v.ty);
      w.varint(v.fields.length); for (const item of v.fields) { writeOperand(w, item); }
      break;
    }
    case "Len": {
      w.varint(8);
      writePlace(w, v.value);
      break;
    }
    case "MakeInterface": {
      w.varint(9);
      writeInterfaceId(w, v.interface);
      writeClassId(w, v.class);
      writePlace(w, v.source);
      break;
    }
    case "TryInterface": {
      w.varint(10);
      writeInterfaceId(w, v.interface);
      writePlace(w, v.source);
      break;
    }
    case "TryClass": {
      w.varint(11);
      writeClassId(w, v.class);
      writePlace(w, v.source);
      break;
    }
    case "InterfaceIsNull": {
      w.varint(12);
      writePlace(w, v.value);
      break;
    }
    case "ArrayPushSlot": {
      w.varint(13);
      writePlace(w, v.value);
      break;
    }
    case "SizeOf": {
      w.varint(14);
      writeTyId(w, v.value);
      break;
    }
    case "AlignOf": {
      w.varint(15);
      writeTyId(w, v.value);
      break;
    }
    case "Select": {
      w.varint(16);
      writeOperand(w, v.cond);
      writeOperand(w, v.ifTrue);
      writeOperand(w, v.ifFalse);
      break;
    }
    case "SimdLoad": {
      w.varint(17);
      writePlace(w, v.source);
      writeTyId(w, v.ty);
      break;
    }
    case "SimdStore": {
      w.varint(18);
      writeOperand(w, v.vector);
      break;
    }
    case "SimdFromParts": {
      w.varint(19);
      w.varint(v.lanes.length); for (const item of v.lanes) { writeOperand(w, item); }
      writeTyId(w, v.ty);
      break;
    }
    case "SimdExtract": {
      w.varint(20);
      writeOperand(w, v.vector);
      w.u8(v.lane);
      break;
    }
    case "SimdSplat": {
      w.varint(21);
      writeOperand(w, v.value);
      writeTyId(w, v.ty);
      break;
    }
    case "SimdBinary": {
      w.varint(22);
      writeSimdBinOp(w, v.op);
      writeOperand(w, v.lhs);
      writeOperand(w, v.rhs);
      break;
    }
    case "SimdUnary": {
      w.varint(23);
      writeSimdUnOp(w, v.op);
      writeOperand(w, v.operand);
      break;
    }
    case "SimdShuffle": {
      w.varint(24);
      writeOperand(w, v.lhs);
      writeOperand(w, v.rhs);
      w.bytes(v.mask);
      writeTyId(w, v.ty);
      break;
    }
    case "SimdFma": {
      w.varint(25);
      writeOperand(w, v.a);
      writeOperand(w, v.b);
      writeOperand(w, v.c);
      break;
    }
  }
}

export function writeBlockId(w: Writer, v: BlockId): void {
  w.varint(v);
}

export function writeUnwindAction(w: Writer, v: UnwindAction): void {
  switch (v.kind) {
    case "Continue": {
      w.varint(0);
      break;
    }
    case "Cleanup": {
      w.varint(1);
      writeBlockId(w, v.value);
      break;
    }
    case "Unreachable": {
      w.varint(2);
      break;
    }
    case "Terminate": {
      w.varint(3);
      break;
    }
  }
}

export function writeStatement(w: Writer, v: Statement): void {
  switch (v.kind) {
    case "Assign": {
      w.varint(0);
      writePlace(w, v.place);
      writeRvalue(w, v.rvalue);
      break;
    }
    case "Init": {
      w.varint(1);
      writePlace(w, v.place);
      writeRvalue(w, v.rvalue);
      break;
    }
    case "Drop": {
      w.varint(2);
      writePlace(w, v.place);
      if (v.flag === null) { w.u8(0); } else { w.u8(1); writeLocalId(w, v.flag!); }
      writeUnwindAction(w, v.unwind);
      break;
    }
    case "StorageLive": {
      w.varint(3);
      writeLocalId(w, v.value);
      break;
    }
    case "StorageDead": {
      w.varint(4);
      writeLocalId(w, v.value);
      break;
    }
    case "SetDropFlag": {
      w.varint(5);
      writeLocalId(w, v.flag);
      w.bool(v.value);
      break;
    }
    case "Nop": {
      w.varint(6);
      break;
    }
  }
}

export function writeSwitchTarget(w: Writer, v: SwitchTarget): void {
  w.varintBig(v.value);
  writeBlockId(w, v.block);
}

export function writeCallee(w: Writer, v: Callee): void {
  switch (v.kind) {
    case "Direct": {
      w.varint(0);
      writeFuncRef(w, v.value);
      break;
    }
    case "Indirect": {
      w.varint(1);
      writeOperand(w, v.operand);
      writeSigId(w, v.sig);
      break;
    }
    case "Virtual": {
      w.varint(2);
      w.varint(v.slot);
      writeSigId(w, v.sig);
      break;
    }
    case "Interface": {
      w.varint(3);
      w.varint(v.slot);
      writeSigId(w, v.sig);
      break;
    }
  }
}

export function writeCallDest(w: Writer, v: CallDest): void {
  writePlace(w, v.place);
  writeBlockId(w, v.target);
}

const AbortReasonIndex: Record<AbortReason, number> = {
  BoundsCheck: 0,
  DivideByZero: 1,
  NullDeref: 2,
  UnwindAcrossBoundary: 3,
};

export function writeAbortReason(w: Writer, v: AbortReason): void {
  w.varint(AbortReasonIndex[v]);
}

export function writeTerminator(w: Writer, v: Terminator): void {
  switch (v.kind) {
    case "Goto": {
      w.varint(0);
      writeBlockId(w, v.value);
      break;
    }
    case "Branch": {
      w.varint(1);
      writeOperand(w, v.cond);
      writeBlockId(w, v.thenBlock);
      writeBlockId(w, v.elseBlock);
      break;
    }
    case "Switch": {
      w.varint(2);
      writeOperand(w, v.discr);
      w.varint(v.targets.length); for (const item of v.targets) { writeSwitchTarget(w, item); }
      writeBlockId(w, v.default);
      break;
    }
    case "Call": {
      w.varint(3);
      writeCallee(w, v.callee);
      w.varint(v.args.length); for (const item of v.args) { writeOperand(w, item); }
      if (v.destination === null) { w.u8(0); } else { w.u8(1); writeCallDest(w, v.destination!); }
      writeUnwindAction(w, v.unwind);
      break;
    }
    case "Return": {
      w.varint(4);
      break;
    }
    case "Unreachable": {
      w.varint(5);
      break;
    }
    case "Resume": {
      w.varint(6);
      break;
    }
    case "Abort": {
      w.varint(7);
      writeAbortReason(w, v.value);
      break;
    }
  }
}

export function writeBlock(w: Writer, v: Block): void {
  writeBlockKind(w, v.kind);
  w.varint(v.statements.length); for (const item of v.statements) { writeStatement(w, item); }
  writeTerminator(w, v.terminator);
}

export function writeFunction(w: Writer, v: Function): void {
  writeSymId(w, v.name);
  writeSigId(w, v.sig);
  writeLinkage(w, v.linkage);
  w.varint(v.locals.length); for (const item of v.locals) { writeLocalDecl(w, item); }
  w.varint(v.blocks.length); for (const item of v.blocks) { writeBlock(w, item); }
  writeSpan(w, v.span);
}

export function writeModule(w: Writer, v: Module): void {
  w.varintBig(v.schemaFingerprint);
  writeSymId(w, v.name);
  w.varint(v.strings.length); for (const item of v.strings) { w.str(item); }
  w.varint(v.files.length); for (const item of v.files) { w.str(item); }
  w.varint(v.types.length); for (const item of v.types) { writeTyDef(w, item); }
  w.varint(v.structs.length); for (const item of v.structs) { writeStructDef(w, item); }
  w.varint(v.classes.length); for (const item of v.classes) { writeClassDef(w, item); }
  w.varint(v.interfaces.length); for (const item of v.interfaces) { writeInterfaceDef(w, item); }
  w.varint(v.sigs.length); for (const item of v.sigs) { writeSignature(w, item); }
  w.varint(v.externs.length); for (const item of v.externs) { writeExternFunc(w, item); }
  w.varint(v.globals.length); for (const item of v.globals) { writeGlobal(w, item); }
  w.varint(v.funcs.length); for (const item of v.funcs) { writeFunction(w, item); }
}

/** Encode a module for the trip across the napi boundary. */
export function encodeModule(module: Module): Uint8Array {
  const w = new Writer();
  writeModule(w, module);
  return w.finish();
}
