/**
 * Generate the `declare module "std/linalg"` block of `global.d.ts`.
 *
 * DECISIONS §22. The declarations and the lowering table are the same list, and
 * writing it twice is how a `dvec3` comes to have a method the compiler does
 * not implement — `TS2339` at the call site, or `GF0001` under a name the
 * editor offered in its completion list. So one table in
 * `packages/checker/src/linalg.ts` produces both, exactly as the Rust MIR
 * definitions produce `mir.generated.ts` and its encoder.
 *
 * Run it with `bun run build:linalg`. The output is spliced between the markers
 * below, so re-running is idempotent and the rest of `global.d.ts` — which is
 * hand-written and stays that way — is never touched.
 *
 * A note on what is *not* generated: the padding field of an `aligned_` type.
 * It is a field in the layout, because trailing space that is not a field is
 * space the layout engine would not reserve, and it is deliberately absent from
 * the declaration, because it is not a component and naming it would invite
 * someone to write to it.
 */

import {
    LINALG_TYPES,
    type LinalgCtor,
    type LinalgOp,
    type LinalgType,
    appliesTo,
    columnTypeOf,
    ctorsFor,
    hasMutatingForm,
    mutatingName,
    opsFor,
} from "@goblin-forge/checker";

const BEGIN = "// <generated by gen-linalg.ts — do not edit by hand>";
const END = "// </generated by gen-linalg.ts>";

/** How a component's type is spelled in TypeScript. */
function scalar(type: LinalgType): string {
    return type.element === "bool" ? "boolean" : type.element;
}

/** A matrix's column type, or a vector itself. */
function columnName(type: LinalgType): string {
    return columnTypeOf(type)?.name ?? type.name;
}

/**
 * The unpadded three-component vector of the same element.
 *
 * What a translation, a scale and a rotation axis are: a `dmat4` transforms
 * homogeneous `dvec4` columns, but the *parameters* of an affine transform are
 * three numbers, not four.
 */
function axisName(type: LinalgType): string {
    return `${type.prefix}vec3`;
}

/** What one component of an operation's parameter list is called. */
const OP_PARAM_NAMES: Partial<Record<string, readonly string[]>> = {
    lerp: ["other", "t"],
    addScaled: ["other", "t"],
    clamp: ["low", "high"],
    scale: ["by"],
    mulVec: ["v"],
};

/** The parameter list of an operation's *instance* form. */
function params(op: LinalgOp, type: LinalgType): string {
    const names = OP_PARAM_NAMES[op.name] ?? ["other"];
    return op.params
        .map((param, index) => {
            const name = names[index] ?? `p${index}`;
            const spelling =
                param === "vector"
                    ? type.name
                    : param === "column"
                        ? columnName(type)
                        : scalar(type);
            return `${name}: ${spelling}`;
        })
        .join(", ");
}

/** What an operation or a constructor hands back, as written. */
function returns(op: LinalgOp, type: LinalgType): string {
    switch (op.returns) {
        case "vector":
            return type.name;
        case "column":
            return columnName(type);
        case "scalar":
            return scalar(type);
        case "bool":
            return "boolean";
    }
}

/** The parameter list of a constructor. */
function ctorParams(ctor: LinalgCtor, type: LinalgType): string {
    // `fromColumns` takes one parameter per column, so its list is a function
    // of the matrix's order rather than of the table row.
    if (ctor.kind === "columns") {
        return type.components.map((column) => `${column}: ${columnName(type)}`).join(", ");
    }
    return ctor.params
        .map((param, index) => {
            const name = ctor.names?.[index] ?? `p${index}`;
            const spelling =
                param === "scalar"
                    ? scalar(type)
                    : param === "axis"
                        ? axisName(type)
                        : param === "column"
                            ? columnName(type)
                            : type.name;
            return `${name}: ${spelling}`;
        })
        .join(", ");
}

/** The types `T.from(…)` accepts: same family and same shape. */
function conversionSources(type: LinalgType): LinalgType[] {
    return [...LINALG_TYPES.values()].filter(
        (other) =>
            other.name !== type.name &&
            other.family === type.family &&
            other.components.length === type.components.length,
    );
}

function declareType(type: LinalgType): string {
    const out: string[] = [];
    const name = type.name;
    const element = scalar(type);
    const size = type.components.length;

    const width = type.element === "f32" ? 4 : 8;
    const packedName = name.replace("aligned_", "");
    const hasPaddedForm = LINALG_TYPES.has(`aligned_${name}`);
    const column = columnTypeOf(type);
    const bytes =
        column === undefined
            ? type.fields.length * width
            : type.fields.length * column.fields.length * width;

    out.push("/**");
    if (column !== undefined) {
        out.push(` * \`${name}\` — a ${size}x${size} matrix: ${size} \`${column.name}\` columns.`);
        out.push(" *");
        out.push(" * **Column-major, with column vectors.** `m.c0` is the first column and");
        out.push(" * `a.mul(b)` applies `b` first, which is GLM's convention and therefore what");
        out.push(" * every shader and every piece of reference code assumes.");
        out.push(" *");
        if (type.padded) {
            out.push(
                ` * Each column carries a lane of padding: ${bytes} bytes against \`${packedName}\`'s`,
            );
            out.push(
                ` * ${size * size * width}, and every column operation is one instruction rather than two.`,
            );
        } else {
            out.push(` * ${bytes} bytes, packed — the layout a graphics API expects.`);
            if (hasPaddedForm) {
                out.push(` * \`aligned_${name}\` is the same maths with padded columns, and faster.`);
            }
        }
    } else {
        out.push(
            ` * \`${name}\` — ${size} \`${element}\`${type.padded ? ", padded to a whole register" : ""}.`,
        );
        out.push(" *");
        if (type.padded) {
            out.push(" * Carries a lane of padding, so arithmetic is one instruction rather than a");
            out.push(` * 128-bit operation and a scalar one. ${bytes} bytes against`);
            out.push(` * \`${packedName}\`'s ${size * width}: faster in a loop, wasteful in a vertex`);
            out.push(" * buffer. Pick deliberately.");
        } else {
            out.push(
                ` * Exactly ${size} components and no padding — ${bytes} bytes — so an array of`,
            );
            out.push(" * them is the layout a vertex buffer wants.");
            if (hasPaddedForm) {
                out.push(
                    ` * \`aligned_${name}\` is the same maths with a lane of padding, and faster.`,
                );
            }
        }
    }
    out.push(" */");
    // `export class`, not `declare class`: this is already an ambient context,
    // so `declare` is an error here — and without `export` the name cannot be
    // imported from the module at all.
    out.push(`export class ${name} {`);
    // A private member, so the type is **nominal**.
    //
    // Without it `dvec3` and `aligned_dvec3` are the same type to tsc: they
    // declare the same components and the same methods, and structural typing
    // has nothing left to tell them apart. `packed.add(padded)` would then
    // type-check and lower a three-lane operation over a four-lane value — a
    // wrong answer, silently, in the one place the two types exist to keep
    // apart. Two private members are compatible only when they come from the
    // same declaration, which is exactly the rule wanted here.
    out.push(`    private readonly __linalg: "${name}";`);
    out.push("");
    // A matrix's constructor takes its columns; a vector's takes its
    // components. Both are the fields the user can name, which is what
    // `components` is.
    const memberType = column === undefined ? element : column.name;
    out.push(
        `    constructor(${type.components.map((c) => `${c}: ${memberType}`).join(", ")});`,
    );
    out.push("");
    for (const component of type.components) {
        out.push(`    ${component}: ${memberType};`);
    }
    out.push("");
    // `m[0]` is `m.c0` and `v[1]` is `v.y`, which is how a shader writes it.
    // Only a *literal* index compiles — the components are fields rather than
    // elements at a stride, and a padded type's are not even evenly spaced — so
    // this signature is wider than what is accepted, and the compiler says so
    // with a caret rather than tsc saying nothing.
    out.push(`    [index: number]: ${memberType};`);
    out.push("");

    // -- constructors -------------------------------------------------------
    for (const ctor of ctorsFor(type)) {
        if (ctor.kind === "unit") {
            for (const [index, component] of type.components.entries()) {
                out.push(`    /** The ${component}-axis: 1 in component ${index}, 0 elsewhere. */`);
                out.push(`    static unit${component.toUpperCase()}(): ${name};`);
                out.push("");
            }
            continue;
        }
        if (ctor.kind === "from") {
            const sources = conversionSources(type);
            if (sources.length === 0) {
                continue;
            }
            out.push("    /**");
            out.push(
                `     * Convert from another ${column === undefined ? `${size}-component vector` : `${size}x${size} matrix`}.`,
            );
            out.push("     *");
            out.push("     * Explicit because nothing here converts on its own: an `fvec3` is not a");
            out.push("     * narrower `dvec3`, and a conversion that costs precision should cost a");
            out.push("     * word at the site that pays for it.");
            out.push("     */");
            for (const source of sources) {
                out.push(`    static from(value: ${source.name}): ${name};`);
            }
            out.push("");
            continue;
        }
        if (ctor.doc !== undefined) {
            out.push(`    /** ${ctor.doc} */`);
        }
        out.push(`    static ${ctor.name}(${ctorParams(ctor, type)}): ${name};`);
        out.push("");
    }

    // -- operations ---------------------------------------------------------
    for (const op of opsFor(type)) {
        if (!appliesTo(op, type)) {
            continue;
        }
        const instance = params(op, type);
        const staticParams = [`a: ${name}`, ...(instance === "" ? [] : [instance.replace(/^other:/, "b:")])]
            .join(", ");
        out.push(`    static ${op.name}(${staticParams}): ${returns(op, type)};`);
        out.push(`    ${op.name}(${instance}): ${returns(op, type)};`);
        if (hasMutatingForm(op)) {
            // Returns a reference to the receiver, so mutations chain. It is
            // deliberately not guarded against aliasing: this is an unsafe
            // language, and a value of three doubles is not where that argument
            // gets relitigated (DECISIONS §22).
            out.push(`    ${mutatingName(op)}(${instance}): Reference<${name}>;`);
        }
        out.push("");
    }

    // Trailing blank line inside the class body reads badly; drop it.
    while (out.at(-1) === "") {
        out.pop();
    }
    out.push("}");
    return out.join("\n");
}

function block(): string {
    const out: string[] = [];
    out.push(BEGIN);
    out.push("//");
    out.push("// Regenerate with `bun run build:linalg` after changing");
    out.push("// `packages/checker/src/linalg.ts`, which is where these come from.");
    out.push("");
    out.push('declare module "std/linalg" {');
    const bodies = [...LINALG_TYPES.values()].map((type) =>
        declareType(type)
            .split("\n")
            .map((line) => (line === "" ? "" : `    ${line}`))
            .join("\n"),
    );
    out.push(bodies.join("\n\n"));
    out.push("}");
    out.push("");
    out.push(END);
    return out.join("\n");
}

const path = new URL("../global.d.ts", import.meta.url);
const existing = await Bun.file(path).text();

const header = [
    "",
    "// ---------------------------------------------------------------------------",
    "// std/linalg",
    "//",
    "// GLM's shape, for a language with no operator overloading: `dvec3.add(a, b)`",
    "// returns a copy, `a.add(b)` returns a copy, and `a.addMut(b)` mutates in place",
    "// and hands back a reference so mutations chain.",
    "//",
    "// A type's *storage* is a plain struct — `dvec3` is three `f64` and nothing",
    "// else, which is what a vertex buffer holds and what crosses the C boundary.",
    "// Its *arithmetic* goes through the vector unit, and the `aligned_` forms are",
    "// padded to a whole register so that arithmetic is one instruction rather than",
    "// two. Nothing converts implicitly, in either direction.",
    "//",
    "// DECISIONS §22 is the reasoning. This block is generated; see gen-linalg.ts.",
    "// ---------------------------------------------------------------------------",
    "",
].join("\n");

const begun = existing.indexOf(BEGIN);
const ended = existing.indexOf(END);
const generated = `${header}${block()}\n`;

const updated =
    begun === -1 || ended === -1
        ? `${existing.trimEnd()}\n${generated}`
        : `${existing.slice(0, begun)}${block()}\n${existing.slice(ended + END.length + 1)}`;

await Bun.write(path, updated);

const types = LINALG_TYPES.size;
const ops = [...LINALG_TYPES.values()].reduce(
    (total, type) =>
        total +
        opsFor(type)
            .filter((op) => appliesTo(op, type))
            .reduce((perType, op) => perType + 2 + (hasMutatingForm(op) ? 1 : 0), 0),
    0,
);
const vectors = [...LINALG_TYPES.values()].filter((type) => type.family === "vec").length;
console.log(
    `wrote std/linalg: ${types} types (${vectors} vector, ${types - vectors} matrix), ` +
    `${ops} methods`,
);
