/**
 * Build `goblin-forge` — the whole compiler as one executable.
 *
 * Two steps, and the first is codegen for the same reason the MIR bindings are:
 * the files the compiler ships with have to be *inside* the binary, and the
 * only way to keep their names is to carry their contents and write them back
 * out. `src/embedded.generated.ts` is that carrier.
 *
 *   bun run packages/cli/build.ts
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..");
const runtime = join(repo, "packages", "runtime");

const sources = {
    globalDeclarations: join(runtime, "global.d.ts"),
    tsconfigBase: join(runtime, "tsconfig.base.json"),
    runtimeCargo: join(runtime, "native", "Cargo.toml"),
    runtimeSource: join(runtime, "native", "src", "lib.rs"),
} as const;

const generated = [
    "// Generated by packages/cli/build.ts. Do not edit.",
    "//",
    "// The files the compiler ships with, as text, so that a single-file",
    "// executable can write them back out under the names their readers expect.",
    "",
    "export const EMBEDDED = {",
    ...Object.entries(sources).map(
        ([name, path]) => `  ${name}: ${JSON.stringify(readFileSync(path, "utf8"))},`,
    ),
    "} as const;",
    "",
].join("\n");

const target = join(here, "src", "embedded.generated.ts");
writeFileSync(target, generated, "utf8");
console.log(`generated ${target} (${(generated.length / 1024).toFixed(1)} KiB)`);

// The addon's file name carries the platform triple, so which one to embed is
// only known here. Generated for that reason, and because an `import … with
// { type: "file" }` of a `.node` is not something TypeScript can resolve — the
// generated file is outside the typecheck for the same reason the MIR bindings
// are inside it: this one has nothing worth checking.
const addon = readdirSync(join(repo, "packages", "backend")).find((file) => file.endsWith(".node"));
if (addon === undefined) {
    console.error(
        "no built addon in packages/backend. Run `bun run build:backend` first.",
    );
    process.exit(1);
}

writeFileSync(
    join(here, "src", "addon.generated.ts"),
    `// Generated by packages/cli/build.ts. Do not edit.
//
// Stands in for \`packages/backend/binding.js\`, which napi generates and which
// finds its \`.node\` by searching the filesystem beside itself. Inside a
// single-file executable there is no "beside itself", and the failure is a
// message about npm's optional dependencies that has nothing to do with what
// went wrong. The addon itself embeds fine: Bun loads a \`.node\` out of a
// compiled binary, so only the search had to go.

import { createRequire } from "node:module";

import addonPath from "../../backend/${addon}" with { type: "file" };

const addon = createRequire(import.meta.url)(addonPath);

export const Backend = addon.Backend;
export const outputExtension = addon.outputExtension;
export const schemaFingerprint = addon.schemaFingerprint;
`,
    "utf8",
);
console.log(`generated addon shim for ${addon}`);

const outfile = join(repo, "bin", process.platform === "win32" ? "goblin-forge.exe" : "goblin-forge");

const result = await Bun.build({
    entrypoints: [join(here, "src", "main.ts")],
    compile: {outfile},
    // The napi loader resolves its `.node` by walking the filesystem, which has
    // nothing to walk inside an executable. This replaces it with a shim that
    // loads the copy Bun embedded.
    plugins: [
        {
            name: "goblin-embed-addon",
            setup(build) {
                build.onResolve({filter: /(^|[\\/])binding\.js$/}, () => ({
                    path: join(here, "src", "addon.generated.ts"),
                }));
            },
        },
    ],
});

if (!result.success) {
    for (const log of result.logs) {
        console.error(log);
    }
    process.exit(1);
}
console.log(`built ${outfile}`);
