/**
 * Build `goblin-forge` — the whole compiler as one executable.
 *
 * Two steps, and the first is codegen for the same reason the MIR bindings are:
 * the files the compiler ships with have to be *inside* the binary, and the
 * only way to keep their names is to carry their contents and write them back
 * out. `src/embedded.generated.ts` is that carrier.
 *
 *   bun run packages/cli/build.ts
 */

import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, "..", "..");
const runtime = join(repo, "packages", "runtime");

const sources = {
    globalDeclarations: join(runtime, "global.d.ts"),
    buildDeclarations: join(runtime, "build-config.d.ts"),
    tsconfigBase: join(runtime, "tsconfig.base.json"),
    runtimeCargo: join(runtime, "native", "Cargo.toml"),
    runtimeSource: join(runtime, "native", "src", "lib.rs"),
} as const;

/**
 * The std modules that are real Goblin source, read off the directory.
 *
 * Enumerated rather than listed, because a hand-written list is a second copy of
 * a directory's contents that nothing keeps honest — the same argument the addon
 * shim below makes about its exports, and the same failure it had: a file added
 * and not listed here would resolve in a checkout and be missing from the
 * shipped executable, where the symptom is tsc reporting that `std/collection`
 * does not exist.
 */
const stdModules = Object.fromEntries(
    readdirSync(join(runtime, "std"))
        .filter((file) => file.endsWith(".ts"))
        .sort()
        .map((file) => [file, readFileSync(join(runtime, "std", file), "utf8")]),
);

const generated = [
    "// Generated by packages/cli/build.ts. Do not edit.",
    "//",
    "// The files the compiler ships with, as text, so that a single-file",
    "// executable can write them back out under the names their readers expect.",
    "",
    "export const EMBEDDED = {",
    ...Object.entries(sources).map(
        ([name, path]) => `  ${name}: ${JSON.stringify(readFileSync(path, "utf8"))},`,
    ),
    "  stdModules: {",
    ...Object.entries(stdModules).map(
        ([file, contents]) => `    ${JSON.stringify(file)}: ${JSON.stringify(contents)},`,
    ),
    "  },",
    "} as const;",
    "",
].join("\n");

const target = join(here, "src", "embedded.generated.ts");
writeFileSync(target, generated, "utf8");
console.log(`generated ${target} (${(generated.length / 1024).toFixed(1)} KiB)`);

// The addon's file name carries the platform triple, so which one to embed is
// only known here. Generated for that reason, and because an `import … with
// { type: "file" }` of a `.node` is not something TypeScript can resolve — the
// generated file is outside the typecheck for the same reason the MIR bindings
// are inside it: this one has nothing worth checking.
const addon = readdirSync(join(repo, "packages", "backend")).find((file) => file.endsWith(".node"));
if (addon === undefined) {
    console.error(
        "no built addon in packages/backend. Run `bun run build:backend` first.",
    );
    process.exit(1);
}

// **What it re-exports is asked of the addon, not typed out.** The shim has to
// name every binding, because a `require` of a `.node` yields an object and
// there is no `export *` from one. Hand-listing them made this a second copy of
// the addon's surface that nothing kept honest: adding `locateLinker` in Rust
// left the bundle referring to a name that was never bound, and the failure was
// a `ReferenceError` from inside the executable rather than anything at build
// time. Loading the addon here — it is the host's, and this is the host —
// makes the list a function of the thing it mirrors.
const exported = Object.keys(createRequire(import.meta.url)(join(repo, "packages", "backend", addon)))
    .filter((name) => name !== "default")
    .sort();

writeFileSync(
    join(here, "src", "addon.generated.ts"),
    `// Generated by packages/cli/build.ts. Do not edit.
//
// Stands in for \`packages/backend/binding.js\`, which napi generates and which
// finds its \`.node\` by searching the filesystem beside itself. Inside a
// single-file executable there is no "beside itself", and the failure is a
// message about npm's optional dependencies that has nothing to do with what
// went wrong. The addon itself embeds fine: Bun loads a \`.node\` out of a
// compiled binary, so only the search had to go.
//
// The exports below are whatever the addon exported when this was generated.

import { createRequire } from "node:module";

import addonPath from "../../backend/${addon}" with { type: "file" };

const addon = createRequire(import.meta.url)(addonPath);

${exported.map((name) => `export const ${name} = addon.${name};`).join("\n")}
`,
    "utf8",
);
console.log(`generated addon shim for ${addon} (${exported.join(", ")})`);

const outfile = join(repo, "bin", process.platform === "win32" ? "goblin-forge.exe" : "goblin-forge");

const result = await Bun.build({
    entrypoints: [join(here, "src", "main.ts")],
    compile: {outfile},
    // The napi loader resolves its `.node` by walking the filesystem, which has
    // nothing to walk inside an executable. This replaces it with a shim that
    // loads the copy Bun embedded.
    plugins: [
        {
            name: "goblin-embed-addon",
            setup(build) {
                build.onResolve({filter: /(^|[\\/])binding\.js$/}, () => ({
                    path: join(here, "src", "addon.generated.ts"),
                }));
            },
        },
    ],
});

if (!result.success) {
    for (const log of result.logs) {
        console.error(log);
    }
    process.exit(1);
}
console.log(`built ${outfile}`);
